name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      # Since it's a pnpm workspace, SonarCloud often benefits from 
      # having the dependencies installed to resolve imports correctly.
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=UOM-GroupAssignments_charmBookingBackendMicroServices
            -Dsonar.organization=uom-groupassignments
            -Dsonar.sources=api_gateway/src,booking/src,user/src,libs/common/src
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/test/**
          projectBaseDir: .